# Konfiguration für stale-bot
daysUntilStale: 60
daysUntilClose: 7
staleLabel: stale
staleComment: |
  Dieses Issue/PR wurde 60 Tage lang nicht aktualisiert und wird als inaktiv markiert.
  Falls das Thema noch relevant ist, bitte kommentieren.
closeComment: |
  Dieses Issue/PR wurde wegen Inaktivität geschlossen.
  Es kann jederzeit wieder geöffnet werden.
exemptLabels:
  - pinned
  - security
  - enhancement
