#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Copyright (c) 2026 Lukas Geiger

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

"""
Tool: c_code_generator
Version: 1.0.0
Author: BACH Team
Created: 2026-02-04
Updated: 2026-02-04
Anthropic-Compatible: True

VERSIONS-HINWEIS: Prüfe auf neuere Versionen mit: bach tools version c_code_generator

Description:
    [Beschreibung hinzufügen]

Usage:
    python c_code_generator.py [args]
"""

__version__ = "1.0.0"
__author__ = "BACH Team"

# -*- coding: utf-8 -*-
"""
Code-Generator Modul für Entwickler-Agent
Phase 2: Core Features

Generiert Python-Code basierend auf Templates und Spezifikationen
"""

import json
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime
from string import Template


class CodeGenerator:
    """Code-Generierungs-Engine"""
    
    # Standard-Templates
    TEMPLATES = {
        "function": '''def ${name}(${params})${return_hint}:
    """${docstring}"""
    ${body}
''',
        "class": '''class ${name}${bases}:
    """${docstring}"""
    
    def __init__(self${init_params}):
        ${init_body}
''',
        "method": '''    def ${name}(self${params})${return_hint}:
        """${docstring}"""
        ${body}
''',
        "module_header": '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
${module_name}
${description}

Generated by RecludOS Entwickler-Agent
Date: ${date}
"""

${imports}

''',
        "cli_main": '''
def main():
    """CLI Entry Point"""
    import argparse
    
    parser = argparse.ArgumentParser(description="${description}")
    ${arguments}
    args = parser.parse_args()
    
    ${main_body}


if __name__ == "__main__":
    main()
''',
        "dataclass": '''@dataclass
class ${name}:
    """${docstring}"""
    ${fields}
''',
        "test_function": '''def test_${name}():
    """Test für ${target}"""
    # Arrange
    ${arrange}
    
    # Act
    ${act}
    
    # Assert
    ${assertions}
''',
        "exception": '''class ${name}(${base}):
    """${docstring}"""
    pass
'''
    }
    
    def __init__(self, templates_dir: str = None):
        self.custom_templates = {}
        if templates_dir:
            self._load_custom_templates(templates_dir)
    
    def _load_custom_templates(self, templates_dir: str):
        """Lädt benutzerdefinierte Templates"""
        path = Path(templates_dir)
        if path.exists():
            for template_file in path.glob("*.template"):
                name = template_file.stem
                self.custom_templates[name] = template_file.read_text(encoding='utf-8')
    
    def generate_function(self, name: str, params: List[Dict] = None,
                         return_type: str = None, docstring: str = "",
                         body: str = "pass") -> str:
        """
        Generiert eine Funktion
        
        Args:
            name: Funktionsname
            params: Liste von {"name": str, "type": str, "default": str}
            return_type: Rückgabetyp
            docstring: Dokumentation
            body: Funktionskörper
        """
        # Parameter formatieren
        param_parts = []
        if params:
            for p in params:
                part = p['name']
                if p.get('type'):
                    part += f": {p['type']}"
                if p.get('default'):
                    part += f" = {p['default']}"
                param_parts.append(part)
        
        params_str = ", ".join(param_parts)
        return_hint = f" -> {return_type}" if return_type else ""
        
        template = Template(self.TEMPLATES["function"])
        return template.substitute(
            name=name,
            params=params_str,
            return_hint=return_hint,
            docstring=docstring or f"{name} Funktion",
            body=body
        )
    
    def generate_class(self, name: str, bases: List[str] = None,
                      docstring: str = "", init_params: List[Dict] = None,
                      methods: List[Dict] = None) -> str:
        """
        Generiert eine Klasse
        
        Args:
            name: Klassenname
            bases: Basisklassen
            docstring: Dokumentation
            init_params: __init__ Parameter
            methods: Methoden-Definitionen
        """
        bases_str = f"({', '.join(bases)})" if bases else ""
        
        # Init-Parameter
        init_param_parts = []
        init_body_parts = []
        
        if init_params:
            for p in init_params:
                part = p['name']
                if p.get('type'):
                    part += f": {p['type']}"
                if p.get('default'):
                    part += f" = {p['default']}"
                init_param_parts.append(part)
                init_body_parts.append(f"self.{p['name']} = {p['name']}")
        
        init_params_str = ", " + ", ".join(init_param_parts) if init_param_parts else ""
        init_body_str = "\n        ".join(init_body_parts) if init_body_parts else "pass"
        
        template = Template(self.TEMPLATES["class"])
        class_code = template.substitute(
            name=name,
            bases=bases_str,
            docstring=docstring or f"{name} Klasse",
            init_params=init_params_str,
            init_body=init_body_str
        )
        
        # Methoden hinzufügen
        if methods:
            for method in methods:
                class_code += "\n" + self.generate_method(**method)
        
        return class_code
    
    def generate_method(self, name: str, params: List[Dict] = None,
                       return_type: str = None, docstring: str = "",
                       body: str = "pass") -> str:
        """Generiert eine Methode (für Klassen)"""
        param_parts = []
        if params:
            for p in params:
                part = p['name']
                if p.get('type'):
                    part += f": {p['type']}"
                if p.get('default'):
                    part += f" = {p['default']}"
                param_parts.append(part)
        
        params_str = ", " + ", ".join(param_parts) if param_parts else ""
        return_hint = f" -> {return_type}" if return_type else ""
        
        template = Template(self.TEMPLATES["method"])
        return template.substitute(
            name=name,
            params=params_str,
            return_hint=return_hint,
            docstring=docstring or f"{name} Methode",
            body=body
        )
    
    def generate_module(self, module_name: str, description: str = "",
                       imports: List[str] = None, content: str = "") -> str:
        """Generiert ein vollständiges Python-Modul"""
        imports_str = "\n".join(imports) if imports else ""
        
        template = Template(self.TEMPLATES["module_header"])
        header = template.substitute(
            module_name=module_name,
            description=description,
            date=datetime.now().strftime("%Y-%m-%d"),
            imports=imports_str
        )
        
        return header + content
    
    def generate_cli(self, description: str, arguments: List[Dict] = None,
                    main_body: str = "pass") -> str:
        """Generiert CLI-Main-Block"""
        arg_parts = []
        if arguments:
            for arg in arguments:
                flags = arg.get('flags', [f"--{arg['name']}"])
                flags_str = ", ".join(f'"{f}"' for f in flags)
                
                options = []
                if arg.get('type'):
                    options.append(f"type={arg['type']}")
                if arg.get('default'):
                    options.append(f"default={repr(arg['default'])}")
                if arg.get('help'):
                    options.append(f"help=\"{arg['help']}\"")
                if arg.get('required'):
                    options.append("required=True")
                
                options_str = ", ".join(options)
                arg_parts.append(f"parser.add_argument({flags_str}, {options_str})")
        
        arguments_str = "\n    ".join(arg_parts) if arg_parts else "pass"
        
        template = Template(self.TEMPLATES["cli_main"])
        return template.substitute(
            description=description,
            arguments=arguments_str,
            main_body=main_body
        )
    
    def generate_dataclass(self, name: str, fields: List[Dict],
                          docstring: str = "") -> str:
        """Generiert eine Dataclass"""
        field_parts = []
        for field in fields:
            part = f"{field['name']}: {field.get('type', 'Any')}"
            if field.get('default') is not None:
                part += f" = {repr(field['default'])}"
            field_parts.append(part)
        
        fields_str = "\n    ".join(field_parts)
        
        template = Template(self.TEMPLATES["dataclass"])
        return template.substitute(
            name=name,
            docstring=docstring or f"{name} Datenklasse",
            fields=fields_str
        )
    
    def generate_test(self, name: str, target: str,
                     arrange: str = "# Setup", act: str = "result = None",
                     assertions: str = "assert True") -> str:
        """Generiert eine Test-Funktion"""
        template = Template(self.TEMPLATES["test_function"])
        return template.substitute(
            name=name,
            target=target,
            arrange=arrange,
            act=act,
            assertions=assertions
        )
    
    def generate_from_spec(self, spec: Dict) -> str:
        """
        Generiert Code aus einer Spezifikation
        
        Spec-Format:
        {
            "type": "module|class|function",
            "name": "...",
            ... weitere Parameter je nach Typ
        }
        """
        code_type = spec.get('type', 'function')
        
        generators = {
            'function': self.generate_function,
            'class': self.generate_class,
            'module': self.generate_module,
            'dataclass': self.generate_dataclass,
            'cli': self.generate_cli,
            'test': self.generate_test
        }
        
        if code_type not in generators:
            raise ValueError(f"Unbekannter Code-Typ: {code_type}")
        
        # Typ aus Spec entfernen für **kwargs
        params = {k: v for k, v in spec.items() if k != 'type'}
        return generators[code_type](**params)


# CLI für direkten Aufruf
if __name__ == "__main__":
    gen = CodeGenerator()
    
    # Demo
    print("=== Code-Generator Demo ===\n")
    
    # Funktion generieren
    func = gen.generate_function(
        name="calculate_sum",
        params=[
            {"name": "a", "type": "int"},
            {"name": "b", "type": "int", "default": "0"}
        ],
        return_type="int",
        docstring="Berechnet die Summe von a und b",
        body="return a + b"
    )
    print("--- Funktion ---")
    print(func)
    
    # Klasse generieren
    cls = gen.generate_class(
        name="Calculator",
        docstring="Einfacher Taschenrechner",
        init_params=[
            {"name": "precision", "type": "int", "default": "2"}
        ],
        methods=[
            {
                "name": "add",
                "params": [{"name": "a"}, {"name": "b"}],
                "body": "return a + b"
            }
        ]
    )
    print("--- Klasse ---")
    print(cls)
